[build]
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18.18.2"
  NPM_FLAGS = "--legacy-peer-deps"
  PYTHON_VERSION = "3.8"

# 기존 redirects와 headers는 그대로 유지하고 아래 추가

[[plugins]]
  package = "@netlify/plugin-functions"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# 환경별 설정
[context.production]
  command = "npm ci && npm run build"

[context.deploy-preview]
  command = "npm ci && npm run build"

[context.branch-deploy]
  command = "npm ci && npm run build"
