import { Hairstyle } from './types';

export const portfolioImages: Hairstyle[] = [
  {
    name: 'Wavy Bob',
    url: 'https://storage.googleapis.com/aistudio-hosting/templates/hair-app/style1.jpg',
    isLocal: false,
    gender: 'Female',
    majorCategory: 'B length',
    minorCategory: 'Cheekbone',
  },
  {
    name: 'Long & Straight',
    url: 'https://storage.googleapis.com/aistudio-hosting/templates/hair-app/style2.jpg',
    isLocal: false,
    gender: 'Female',
    majorCategory: 'G length',
    minorCategory: 'None',
  },
  {
    name: 'Pixie Cut',
    url: 'https://storage.googleapis.com/aistudio-hosting/templates/hair-app/style3.jpg',
    isLocal: false,
    gender: 'Female',
    majorCategory: 'A length',
    minorCategory: 'Eyebrow',
  },
  {
    name: 'Curly Afro',
    url: 'https://storage.googleapis.com/aistudio-hosting/templates/hair-app/style4.jpg',
    isLocal: false,
    gender: 'Female',
    majorCategory: 'D length',
    minorCategory: 'None',
  },
  {
    name: 'Slicked Back',
    url: 'https://storage.googleapis.com/aistudio-hosting/templates/hair-app/style5.jpg',
    isLocal: false,
    gender: 'Male',
    majorCategory: 'PUSHED BACK',
    minorCategory: 'Forehead',
  },
  {
    name: 'Red Waves',
    url: 'https://storage.googleapis.com/aistudio-hosting/templates/hair-app/style6.jpg',
    isLocal: false,
    gender: 'Female',
    majorCategory: 'F length',
    minorCategory: 'None',
  },
    {
    name: 'Silver Curls',
    url: 'https://storage.googleapis.com/aistudio-hosting/templates/hair-app/style7.jpg',
    isLocal: false,
    gender: 'Female',
    majorCategory: 'E length',
    minorCategory: 'Cheekbone',
  },
  {
    name: 'Blonde Shag',
    url: 'https://storage.googleapis.com/aistudio-hosting/templates/hair-app/style8.jpg',
    isLocal: false,
    gender: 'Female',
    majorCategory: 'C length',
    minorCategory: 'Eye',
  },
  {
    name: 'Modern Mullet',
    url: 'https://storage.googleapis.com/aistudio-hosting/templates/hair-app/style9.jpg',
    isLocal: false,
    gender: 'Male',
    majorCategory: 'MOHICAN',
    minorCategory: 'None',
  },
];
